//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsBrowserYouTubeLoginTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<style>\r\n  h3,\r\n  h4,\r\n  h5,\r\n  h6,\r\n  body\r\n  {\r\n    font-size: 0.8em;\r\n  }\r\n</s" +
            "tyle>\r\n\r\n## DapperExtensions.NetCore (2.0.7)\r\n### https://www.nuget.org/packages" +
            "/DapperExtensions.NetCore/2.0.7\r\n---\r\n## Dapper (2.0.30)\r\n### https://www.nuget." +
            "org/packages/Dapper/2.0.30\r\n```\r\nThe Dapper library and tools are licenced under" +
            " Apache 2.0: http://www.apache.org/licenses/LICENSE-2.0\r\n\r\nThe Dapper logo is co" +
            "pyright Marc Gravell 2021 onwards; it is fine to use the Dapper logo when refere" +
            "ncing the Dapper library and utilities, but\r\nthe Dapper logo (including derivati" +
            "ves) must not be used in a way that misrepresents an external product or library" +
            " as being affiliated or endorsed\r\nwith Dapper. For example, you must not use the" +
            " Dapper logo as the package icon on your own external tool (even if it uses Dapp" +
            "er internally),\r\nwithout written permission. If in doubt: ask.\r\n```\r\n---\r\n## Sys" +
            "tem.Reflection.Emit.Lightweight (4.6.0)\r\n### https://www.nuget.org/packages/Syst" +
            "em.Reflection.Emit.Lightweight/4.6.0\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c" +
            ") .NET Foundation and Contributors\r\n\r\nAll rights reserved.\r\n\r\nPermission is here" +
            "by granted, free of charge, to any person obtaining a copy\r\nof this software and" +
            " associated documentation files (the \"Software\"), to deal\r\nin the Software witho" +
            "ut restriction, including without limitation the rights\r\nto use, copy, modify, m" +
            "erge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and " +
            "to permit persons to whom the Software is\r\nfurnished to do so, subject to the fo" +
            "llowing conditions:\r\n\r\nThe above copyright notice and this permission notice sha" +
            "ll be included in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SO" +
            "FTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, I" +
            "NCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PA" +
            "RTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGH" +
            "T HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN AC" +
            "TION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH" +
            " THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n## Micro" +
            "soft.CSharp (4.6.0)\r\n### https://www.nuget.org/packages/Microsoft.CSharp/4.6.0\r\n" +
            "```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) .NET Foundation and Contributors\r\n\r\n" +
            "All rights reserved.\r\n\r\nPermission is hereby granted, free of charge, to any per" +
            "son obtaining a copy\r\nof this software and associated documentation files (the \"" +
            "Software\"), to deal\r\nin the Software without restriction, including without limi" +
            "tation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense," +
            " and/or sell\r\ncopies of the Software, and to permit persons to whom the Software" +
            " is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyr" +
            "ight notice and this permission notice shall be included in all\r\ncopies or subst" +
            "antial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WA" +
            "RRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRAN" +
            "TIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. " +
            "IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAM" +
            "AGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, A" +
            "RISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEAL" +
            "INGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n## System.Data.SQLite.Core (1.0.113.7)\r\n### ht" +
            "tps://www.nuget.org/packages/System.Data.SQLite.Core/1.0.113.7\r\n```\r\nPublic Doma" +
            "in\r\n```\r\n---\r\n## Stub.System.Data.SQLite.Core.NetStandard (1.0.113.2)\r\n### https" +
            "://www.nuget.org/packages/Stub.System.Data.SQLite.Core.NetStandard/1.0.113.2\r\n``" +
            "`\r\nPublic Domain\r\n```\r\n---\r\n## System.Security.Cryptography.ProtectedData (5.0.0" +
            ")\r\n### https://www.nuget.org/packages/System.Security.Cryptography.ProtectedData" +
            "/5.0.0\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) .NET Foundation and Contribu" +
            "tors\r\n\r\nAll rights reserved.\r\n\r\nPermission is hereby granted, free of charge, to" +
            " any person obtaining a copy\r\nof this software and associated documentation file" +
            "s (the \"Software\"), to deal\r\nin the Software without restriction, including with" +
            "out limitation the rights\r\nto use, copy, modify, merge, publish, distribute, sub" +
            "license, and/or sell\r\ncopies of the Software, and to permit persons to whom the " +
            "Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe abo" +
            "ve copyright notice and this permission notice shall be included in all\r\ncopies " +
            "or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WI" +
            "THOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO TH" +
            "E WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRIN" +
            "GEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CL" +
            "AIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHE" +
            "RWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OT" +
            "HER DEALINGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n## MahApps.Metro (2.4.5)\r\n### https://" +
            "www.nuget.org/packages/MahApps.Metro/2.4.5\r\n```\r\nMIT License\r\n\r\nCopyright (c) .N" +
            "ET Foundation and Contributors. All rights reserved.\r\n\r\nPermission is hereby gra" +
            "nted, free of charge, to any person obtaining a copy\r\nof this software and assoc" +
            "iated documentation files (the \"Software\"), to deal\r\nin the Software without res" +
            "triction, including without limitation the rights\r\nto use, copy, modify, merge, " +
            "publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to per" +
            "mit persons to whom the Software is\r\nfurnished to do so, subject to the followin" +
            "g conditions:\r\n\r\nThe above copyright notice and this permission notice shall be " +
            "included in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE" +
            " IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDI" +
            "NG BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICUL" +
            "AR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLD" +
            "ERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION O" +
            "F CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE S" +
            "OFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n## ControlzEx " +
            "(4.4.0)\r\n### https://www.nuget.org/packages/ControlzEx/4.4.0\r\n```\r\nThe MIT Licen" +
            "se (MIT)\r\n\r\nCopyright (c) 2015-2019 Jan Karger, Bastian Schmidt\r\n\r\nPermission is" +
            " hereby granted, free of charge, to any person obtaining a copy\r\nof this softwar" +
            "e and associated documentation files (the \"Software\"), to deal\r\nin the Software " +
            "without restriction, including without limitation the rights\r\nto use, copy, modi" +
            "fy, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Software," +
            " and to permit persons to whom the Software is\r\nfurnished to do so, subject to t" +
            "he following conditions:\r\n\r\nThe above copyright notice and this permission notic" +
            "e shall be included in all\r\ncopies or substantial portions of the Software.\r\n\r\nT" +
            "HE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLI" +
            "ED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR" +
            " A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COP" +
            "YRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN " +
            "AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION" +
            " WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.\r\n\r\n```\r\n---\r\n#" +
            "# Microsoft.Xaml.Behaviors.Wpf (1.1.19)\r\n### https://www.nuget.org/packages/Micr" +
            "osoft.Xaml.Behaviors.Wpf/1.1.19\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) 201" +
            "5 Microsoft\r\n\r\nPermission is hereby granted, free of charge, to any person obtai" +
            "ning a copy\r\nof this software and associated documentation files (the \"Software\"" +
            "), to deal\r\nin the Software without restriction, including without limitation th" +
            "e rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or s" +
            "ell\r\ncopies of the Software, and to permit persons to whom the Software is\r\nfurn" +
            "ished to do so, subject to the following conditions:\r\n\r\nThe above copyright noti" +
            "ce and this permission notice shall be included in all\r\ncopies or substantial po" +
            "rtions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF" +
            " ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF M" +
            "ERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVE" +
            "NT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR O" +
            "THER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FR" +
            "OM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN T" +
            "HE\r\nSOFTWARE.\r\n```\r\n---\r\n## System.Text.Json (4.7.2)\r\n### https://www.nuget.org/" +
            "packages/System.Text.Json/4.7.2\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) .NE" +
            "T Foundation and Contributors\r\n\r\nAll rights reserved.\r\n\r\nPermission is hereby gr" +
            "anted, free of charge, to any person obtaining a copy\r\nof this software and asso" +
            "ciated documentation files (the \"Software\"), to deal\r\nin the Software without re" +
            "striction, including without limitation the rights\r\nto use, copy, modify, merge," +
            " publish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to pe" +
            "rmit persons to whom the Software is\r\nfurnished to do so, subject to the followi" +
            "ng conditions:\r\n\r\nThe above copyright notice and this permission notice shall be" +
            " included in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SOFTWAR" +
            "E IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUD" +
            "ING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICU" +
            "LAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOL" +
            "DERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION " +
            "OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE " +
            "SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n## MaterialDe" +
            "signThemes (4.0.0)\r\n### https://www.nuget.org/packages/MaterialDesignThemes/4.0." +
            "0\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) James Willock,  Mulholland Softwa" +
            "re and Contributors\r\n\r\nPermission is hereby granted, free of charge, to any pers" +
            "on obtaining a copy\r\nof this software and associated documentation files (the \"S" +
            "oftware\"), to deal\r\nin the Software without restriction, including without limit" +
            "ation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicense, " +
            "and/or sell\r\ncopies of the Software, and to permit persons to whom the Software " +
            "is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyri" +
            "ght notice and this permission notice shall be included in all\r\ncopies or substa" +
            "ntial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WAR" +
            "RANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANT" +
            "IES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. I" +
            "N NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMA" +
            "GES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, AR" +
            "ISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALI" +
            "NGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n## MaterialDesignColors (2.0.0)\r\n### https://ww" +
            "w.nuget.org/packages/MaterialDesignColors/2.0.0\r\n```\r\nThe MIT License (MIT)\r\n\r\nC" +
            "opyright (c) James Willock,  Mulholland Software and Contributors\r\n\r\nPermission " +
            "is hereby granted, free of charge, to any person obtaining a copy\r\nof this softw" +
            "are and associated documentation files (the \"Software\"), to deal\r\nin the Softwar" +
            "e without restriction, including without limitation the rights\r\nto use, copy, mo" +
            "dify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of the Softwar" +
            "e, and to permit persons to whom the Software is\r\nfurnished to do so, subject to" +
            " the following conditions:\r\n\r\nThe above copyright notice and this permission not" +
            "ice shall be included in all\r\ncopies or substantial portions of the Software.\r\n\r" +
            "\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMP" +
            "LIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS F" +
            "OR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR C" +
            "OPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER I" +
            "N AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTI" +
            "ON WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n#" +
            "# Prism.DryIoc (8.0.0.1909)\r\n### https://www.nuget.org/packages/Prism.DryIoc/8.0" +
            ".0.1909\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) .NET Foundation\r\n\r\nAll righ" +
            "ts reserved. Permission is hereby granted, free of charge, to any person obtaini" +
            "ng a copy of this software and associated documentation files (the \"Software\"), " +
            "to deal in the Software without restriction, including without limitation the ri" +
            "ghts to use, copy, modify, merge, publish, distribute, sublicense, and/or sell c" +
            "opies of the Software, and to permit persons to whom the Software is furnished t" +
            "o do so, subject to the following conditions: \r\n\r\nThe above copyright notice and" +
            " this permission notice shall be included in all copies or substantial portions " +
            "of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KI" +
            "ND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTA" +
            "BILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL " +
            "THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABI" +
            "LITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF " +
            "OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE." +
            "\r\n```\r\n---\r\n## DryIoc.dll (4.5.0)\r\n### https://www.nuget.org/packages/DryIoc.dll" +
            "/4.5.0\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) 2013-2021 Maksim Volkau\r\n\r\nP" +
            "ermission is hereby granted, free of charge, to any person obtaining a copy\r\nof " +
            "this software and associated documentation files (the \"Software\"), to deal\r\nin t" +
            "he Software without restriction, including without limitation the rights\r\nto use" +
            ", copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of t" +
            "he Software, and to permit persons to whom the Software is\r\nfurnished to do so, " +
            "subject to the following conditions:\r\n\r\nThe above copyright notice and this perm" +
            "ission notice shall be included in\r\nall copies or substantial portions of the So" +
            "ftware.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRE" +
            "SS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r" +
            "\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAU" +
            "THORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY," +
            " WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR I" +
            "N CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\r\nTHE SOFTWARE.\r\n`" +
            "``\r\n## Prism.Wpf (8.0.0.1909)\r\n### https://www.nuget.org/packages/Prism.Wpf/8.0." +
            "0.1909\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) .NET Foundation\r\n\r\nAll right" +
            "s reserved. Permission is hereby granted, free of charge, to any person obtainin" +
            "g a copy of this software and associated documentation files (the \"Software\"), t" +
            "o deal in the Software without restriction, including without limitation the rig" +
            "hts to use, copy, modify, merge, publish, distribute, sublicense, and/or sell co" +
            "pies of the Software, and to permit persons to whom the Software is furnished to" +
            " do so, subject to the following conditions: \r\n\r\nThe above copyright notice and " +
            "this permission notice shall be included in all copies or substantial portions o" +
            "f the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIN" +
            "D, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTAB" +
            "ILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL T" +
            "HE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABIL" +
            "ITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF O" +
            "R IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\r" +
            "\n```\r\n---\r\n## Prism.Core (8.0.0.1909)\r\n### https://www.nuget.org/packages/Prism." +
            "Core/8.0.0.1909\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) .NET Foundation\r\n\r\n" +
            "All rights reserved. Permission is hereby granted, free of charge, to any person" +
            " obtaining a copy of this software and associated documentation files (the \"Soft" +
            "ware\"), to deal in the Software without restriction, including without limitatio" +
            "n the rights to use, copy, modify, merge, publish, distribute, sublicense, and/o" +
            "r sell copies of the Software, and to permit persons to whom the Software is fur" +
            "nished to do so, subject to the following conditions: \r\n\r\nThe above copyright no" +
            "tice and this permission notice shall be included in all copies or substantial p" +
            "ortions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY O" +
            "F ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF M" +
            "ERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVEN" +
            "T SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTH" +
            "ER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM," +
            " OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE S" +
            "OFTWARE.\r\n```\r\n---\r\n## ReactiveProperty (7.10.0)\r\n### https://www.nuget.org/pack" +
            "ages/ReactiveProperty/7.10.0\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) 2018 n" +
            "euecc, xin9le, okazuki\r\n\r\nPermission is hereby granted, free of charge, to any p" +
            "erson obtaining a copy\r\nof this software and associated documentation files (the" +
            " \"Software\"), to deal\r\nin the Software without restriction, including without li" +
            "mitation the rights\r\nto use, copy, modify, merge, publish, distribute, sublicens" +
            "e, and/or sell\r\ncopies of the Software, and to permit persons to whom the Softwa" +
            "re is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above cop" +
            "yright notice and this permission notice shall be included in\r\nall copies or sub" +
            "stantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT " +
            "WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARR" +
            "ANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT" +
            ". IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, D" +
            "AMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE," +
            " ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DE" +
            "ALINGS IN\r\nTHE SOFTWARE.\r\n```\r\n---\r\n## ReactiveProperty.Core (7.10.0)\r\n### https" +
            "://www.nuget.org/packages/ReactiveProperty.Core/7.10.0\r\n```\r\nThe MIT License (MI" +
            "T)\r\n\r\nCopyright (c) 2018 neuecc, xin9le, okazuki\r\n\r\nPermission is hereby granted" +
            ", free of charge, to any person obtaining a copy\r\nof this software and associate" +
            "d documentation files (the \"Software\"), to deal\r\nin the Software without restric" +
            "tion, including without limitation the rights\r\nto use, copy, modify, merge, publ" +
            "ish, distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit " +
            "persons to whom the Software is\r\nfurnished to do so, subject to the following co" +
            "nditions:\r\n\r\nThe above copyright notice and this permission notice shall be incl" +
            "uded in\r\nall copies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS " +
            "PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING B" +
            "UT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR P" +
            "URPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS " +
            "BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CO" +
            "NTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTW" +
            "ARE OR THE USE OR OTHER DEALINGS IN\r\nTHE SOFTWARE.\r\n```\r\n---\r\n## System.Componen" +
            "tModel.Annotations (5.0.0)\r\n### https://www.nuget.org/packages/System.ComponentM" +
            "odel.Annotations/5.0.0\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) .NET Foundat" +
            "ion and Contributors\r\n\r\nAll rights reserved.\r\n\r\nPermission is hereby granted, fr" +
            "ee of charge, to any person obtaining a copy\r\nof this software and associated do" +
            "cumentation files (the \"Software\"), to deal\r\nin the Software without restriction" +
            ", including without limitation the rights\r\nto use, copy, modify, merge, publish," +
            " distribute, sublicense, and/or sell\r\ncopies of the Software, and to permit pers" +
            "ons to whom the Software is\r\nfurnished to do so, subject to the following condit" +
            "ions:\r\n\r\nThe above copyright notice and this permission notice shall be included" +
            " in all\r\ncopies or substantial portions of the Software.\r\n\r\nTHE SOFTWARE IS PROV" +
            "IDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT N" +
            "OT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPO" +
            "SE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE L" +
            "IABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILITY, WHETHER IN AN ACTION OF CONTRA" +
            "CT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR IN CONNECTION WITH THE SOFTWARE " +
            "OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.\r\n```\r\n---\r\n## System.Reactive (5." +
            "0.0)\r\n### https://www.nuget.org/packages/System.Reactive/5.0.0\r\n```\r\nThe MIT Lic" +
            "ense (MIT)\r\n\r\nCopyright (c) .NET Foundation and Contributors\r\n\r\nAll rights reser" +
            "ved.\r\n\r\nPermission is hereby granted, free of charge, to any person obtaining a " +
            "copy\r\nof this software and associated documentation files (the \"Software\"), to d" +
            "eal\r\nin the Software without restriction, including without limitation the right" +
            "s\r\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\nco" +
            "pies of the Software, and to permit persons to whom the Software is\r\nfurnished t" +
            "o do so, subject to the following conditions:\r\n\r\nThe above copyright notice and " +
            "this permission notice shall be included in all\r\ncopies or substantial portions " +
            "of the Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KI" +
            "ND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANT" +
            "ABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHAL" +
            "L THE\r\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nL" +
            "IABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOU" +
            "T OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOF" +
            "TWARE.\r\n```\r\n---\r\n## Markdig (0.22.0)\r\n### https://www.nuget.org/packages/Markdi" +
            "g/0.22.0\r\n```\r\nCopyright (c) 2018-2019, Alexandre Mutel\r\nAll rights reserved.\r\n\r" +
            "\nRedistribution and use in source and binary forms, with or without modification" +
            "\r\n, are permitted provided that the following conditions are met:\r\n\r\n1. Redistri" +
            "butions of source code must retain the above copyright notice, this \r\n   list of" +
            " conditions and the following disclaimer.\r\n\r\n2. Redistributions in binary form m" +
            "ust reproduce the above copyright notice, \r\n   this list of conditions and the f" +
            "ollowing disclaimer in the documentation \r\n   and/or other materials provided wi" +
            "th the distribution.\r\n\r\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND C" +
            "ONTRIBUTORS \"AS IS\" AND \r\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT " +
            "LIMITED TO, THE IMPLIED \r\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTIC" +
            "ULAR PURPOSE ARE \r\nDISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIB" +
            "UTORS BE LIABLE\r\nFOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CO" +
            "NSEQUENTIAL \r\nDAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE " +
            "GOODS OR \r\nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HO" +
            "WEVER \r\nCAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABI" +
            "LITY,\r\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE" +
            " USE \r\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\r\n```" +
            "\r\n---\r\n## Markdig.Wpf (0.5.0.1)\r\n### https://www.nuget.org/packages/Markdig.Wpf/" +
            "0.5.0.1\r\n```\r\nThe MIT License (MIT)\r\n\r\nCopyright (c) 2016-2021 Nicolas Musset\r\n\r" +
            "\nPermission is hereby granted, free of charge, to any person obtaining a copy\r\no" +
            "f this software and associated documentation files (the \"Software\"), to deal\r\nin" +
            " the Software without restriction, including without limitation the rights\r\nto u" +
            "se, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\ncopies of" +
            " the Software, and to permit persons to whom the Software is\r\nfurnished to do so" +
            ", subject to the following conditions:\r\n\r\nThe above copyright notice and this pe" +
            "rmission notice shall be included in all\r\ncopies or substantial portions of the " +
            "Software.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXP" +
            "RESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY" +
            ",\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\n" +
            "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\nLIABILIT" +
            "Y, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\nOUT OF OR" +
            " IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\r\nSOFTWARE.\r" +
            "\n```")]
        public string License {
            get {
                return ((string)(this["License"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%LOCALAPPDATA%\\Microsoft\\Edge\\User Data\\Local State")]
        public string EdgeLocalStateFilePath {
            get {
                return ((string)(this["EdgeLocalStateFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%LOCALAPPDATA%\\Microsoft\\Edge\\User Data\\Default\\Cookies")]
        public string EdgeCookiesFilePath {
            get {
                return ((string)(this["EdgeCookiesFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Local State")]
        public string ChromeLocalStateFilePath {
            get {
                return ((string)(this["ChromeLocalStateFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Cookies")]
        public string ChromeCookiesFilePath {
            get {
                return ((string)(this["ChromeCookiesFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".youtube.com")]
        public string HostKey {
            get {
                return ((string)(this["HostKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%APPDATA%\\obs-studio\\plugin_config\\obs-browser\\Cookies")]
        public string ObsCookiesFilePath {
            get {
                return ((string)(this["ObsCookiesFilePath"]));
            }
        }
    }
}
